### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/Atlas#119]
- [x] remove all print statements, from everywhere
- [x] read https://docs.python.org/3/library/logging.html and https://docs.python.org/3/library/logging.config.html
- [x] setup logging in each file, make sure you can log stuff from everywhere
- [x] change `LoggingConfig.py` so anything from any module at any level is printed to file, and anything at `INFO` or above is printed to console

**Comment by Raa37** [comment]
kept print in simUI.py only as it is an exception message

**Comment by twatteyne** [comment]
No, please remove all prints. If it’s a real problem, log a error
