### ISSUE TITLE
RunOneSim main() restructuring

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/Atlas#121]
In RunOneSim, code is divided between main() and runSim() with no apparent reason. Make the following changes:
- [x] rename function `runSim()` to `runOneSim()`
- [x] move all code from `main()` to `runOneSim()`
- [x] call `runOneSim()` from `main()`, i.e. main() should contain only a single line
- [x] call `runOneSim()` from `RunSim()`

**Comment by twatteyne** [comment]
In RunOneSim, code is divided between main() and runSim() with no apparent reason. Make the following changes:
-

**Comment by Raa37** [comment]
I don't understand task 4 , we removed runSim() and replaced with RunOneSim().
Will push changes with first 3 tasks and will create PR once comment is answered/resolved

**Comment by Raa37** [comment]
- Tests don't run here as I created branch from develop and #131 hasn't been merged yet

**Comment by twatteyne** [comment]
In https://github.com/openwsn-berkeley/Atlas/blob/develop_121/RunSim.py#L67, just change
```
RunOneSim.main(simSetting, simUI)
```
to
```
RunOneSim.runOneSim(simSetting, simUI)
```

**Comment by twatteyne** [comment]
to hav the tests run, merge `develop` into `develop_121`. You do that from the command-line onf you computer (or using TortoiseGit). Read https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
