### ISSUE TITLE
simpler RunSim.main()

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/Atlas#126]
The function is too complicated...

- [x] task 1

```
    # log start of simulation
    log.info(f'RunSim starting ...')
```
Just comment "# log" when you log, no need to repeat the same thing you are writing in the message, risk of desync.

- [x] task 2

```
    config = toml.load(pkg_resources.resource_filename(__name__, f"configs/{configfile}.toml"))
    config = config['atlas']

    # create a list of settings, one per simulation run
    simSettings = allSimSettings(config)
``` 

can be much simpler, something like

```
    # create a list of simSettings, one per simulation run
    simSettings = allSimSettings(toml.load(pkg_resources.resource_filename(__name__, f"configs/{configfile}.toml"))['atlas'])
``` 

- [x] task 3

```
simSetting['configFileName'] =  configfile
```

naming! configfile -> configFileName

- [x] task 4

```
simSetting['configFileName'] =  configfile
        simSetting['floorplan']      = pkg_resources.resource_string('maps',
                                             simSetting['floorplan']).decode('utf-8')
```

move this in section "# run simulations, one run per simSetting"

- [x] task 5

```
for (runNum, simSetting) in enumerate(simSettings):
```

you are never using runNum. Change to:

```
for simSetting in simSettings:
```

- [x] task 6

```
cmd    = ["sbatch", "--partition=cpu_homogen", "../RunOneSim.sbatch", str(simSetting)]
            p      = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

you are not using variable `p`, and no need to do two steps, change to

```
subprocess.Popen(
    ["sbatch", "--partition=cpu_homogen", "../RunOneSim.sbatch", str(simSetting)],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)
```

- [x] task 7

```
simUI = None if noui else SimUI.SimUI()
```

Are you intentionally create a UI for every run? If yes, do it in `RunOneSim`; if not, more out of the loop.  It probably makes more sense to create a UI once, even when running multiple runs. Obvisouly test by running multiple runs on your lap with UI.

**Comment by Raa37** [comment]
- Task 6 broke CLEPS. It was because we replace str(simSetting) with json.dumps(simSetting) in #120 so in code below 
json.dumps would be run in linux cmd not python, so RunOneSim.sbatch wasn't being called at all. 
```
subprocess.Popen(
    ["sbatch", "--partition=cpu_homogen", "../RunOneSim.sbatch", json.dumps(simSetting)],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)
```
I fixed this as follows:
```
            simSetting = json.dumps(simSetting)
            subprocess.Popen(["sbatch", "--partition=cpu_homogen", "../RunOneSim.sbatch", simSetting],
                               stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE)
```
