### ISSUE TITLE
cleaner error handling in SimEngine

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/Atlas#130]
The error handling in `SimEngine` is a mess. Instead of the super convoluted way to using a kpi variable, etc:

- [x] in `RunOneSim.runSim()` remove the `timeToFullMapping` handling, creatio and return of `kpis`. The function should end with the destroy() statements
- [x] in `RunOneSim.main()` remove the collection and handling of `kpis`. The function should end with `runSim(simSetting, simUI)`
- [x] in `SimEngine`, remove anything to do with `dataCollector`. Keep the try/except statements in `run()`, but just `log.info()` when simulation ends normally, `log.critical()` when not.

**Comment by Raa37** [comment]
For task 3, didn't we want to log the error in the data collector to be able to know which run failed and with what config and seed so we could replicate it ? 
In Atlas.log, how do we tell different simulations apart, as all runs will be writing to the same file?

**Comment by twatteyne** [comment]
I don't see a fix for the following in your PR

- in RunOneSim.runSim() remove the timeToFullMapping handling, creatio and return of kpis. The function should end with the destroy() statements
- in RunOneSim.main() remove the collection and handling of kpis. The function should end with runSim(simSetting, simUI)
