### ISSUE TITLE
why installing toml in python-app.yml?

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/Atlas#144]
in `python-app.yml`, why do you manually `pip install toml`?

**Comment by Raa37** [comment]
Builds kept failing because it "couldn't find toml module", I thought by doing that I was adding it to the requirements.

**Comment by twatteyne** [comment]
no. All requirements go in `requirements.txt`, adding this fixes the build (in the most convoluted way), but people using your code will find it doensn't work, because all they do it `pip install -r requirements`. Add toml to `requirements.txt`, remvoe from ` python-app.yml`
