### ISSUE TITLE
have DotBots change direction mid-course

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/Atlas#154]
have orchesration randomly set all DotBots' heading each second

**Comment by Raa37** [comment]
Everytime the DotBots receive a new command:
- previously scheduled bump is canceled from events in simEngine.
-  Dotbots adjust their movement (heading + speed) whenever 

[ One thing is that if speed is 1m/s and they get 1 cmd/s they change their trajectory but hardly move, so I changed command to set random speeds as well to get to see them moving properly ]
