### ISSUE TITLE
orchestrator declares run as finished

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/Atlas#158]
- simulator switches to the next run when complete
- simulator exits when all run complete

**Comment by Raa37** [comment]
determined when all obstacle cells are frontier cells and no explored cells are frontier cells

**Comment by Raa37** [comment]
need to choose what to do with cells where the robot bumps exactly on the corner, as for now we do not add obstacle cells in those scenarios but frontier cells are added in all directions so we have frontier cells that are never removd because they are hidden behind obstacles and are not reachable
