### ISSUE TITLE
add Frontier cells to UI

### ISSUE THREAD

**Issue by Raa37** [openwsn-berkeley/Atlas#182]

**Comment by Raa37** [comment]
cellsFrontier -> red cells on UI/map

**Comment by twatteyne** [comment]
This is probably a duplicate of #181?

**Comment by Raa37** [comment]
> 

- This issue is just for representing frontiers cells as red cells in UI, it's that starting step for #183 which is why i'm using the same branch for both and will create one pull request for the both of them together.
