### ISSUE TITLE
orchestrator tracks frontier cells

### ISSUE THREAD

**Issue by Raa37** [openwsn-berkeley/Atlas#183]
frontier cells expand like elastic band around explored cells

**Comment by Raa37** [comment]
- frontier cells at corners on obstacles are never removed as they are never identifies as obstacles since we reject cells that are exactly on corners.
- need to optimise, current frontier computation is slow, further down the line this will make everything else much slower

**Comment by twatteyne** [comment]
About

>frontier cells at corners on obstacles are never removed as they are never identifies as obstacles since we reject cells that are exactly on corners

This isn't true. Frontier cells in the corner are added if you bump into any of their neighboring cells.

**Comment by Raa37** [comment]
> About
> 
> > frontier cells at corners on obstacles are never removed as they are never identifies as obstacles since we reject cells that are exactly on corners
> 
> This isn't true. Frontier cells in the corner are added if you bump into any of their neighboring cells.

I meant that they don't get 'explored' and added as obstacle which means that they remain frontier cells. I am fixing this by detecting these particular frontiers and removing them.
