### ISSUE TITLE
dots don't connect to lines

### ISSUE THREAD

**Issue by Raa37** [openwsn-berkeley/Atlas#83]
![image](https://user-images.githubusercontent.com/48555638/110001630-d6b5f900-7d14-11eb-8851-6f2dda699ff9.png)

in this case, the cell is correctly identified but it doesn't connect to the lines , as a dot can only connect to a dot to form a line.
in cases like this Atlas runs out if frontiers and targets to provide, as are truly has been mapped, however, completion isnt identified

**Comment by twatteyne** [comment]
Agreed! THis seems to be a bug in the logic of `_consolidateMap()`

**Comment by Raa37** [comment]
![image](https://user-images.githubusercontent.com/48555638/110309349-86cf7e80-8001-11eb-8e84-b785f18d2e5e.png)

Fixed

**Comment by Raa37** [comment]
![image](https://user-images.githubusercontent.com/48555638/110309484-b088a580-8001-11eb-80f1-3fd20cc004c3.png)

Fixed.
